//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasques.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERVALUES
    {
        public int IDUSERVALUE { get; set; }
        public string VALUENAME { get; set; }
        public string VALUE { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public Nullable<int> IDTASK { get; set; }
        public Nullable<int> ORDER { get; set; }
    }
}
