//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasques.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERTASK
    {
        public int IDUSERTASK { get; set; }
        public int IDTASK { get; set; }
        public int IDUSER { get; set; }
        public string TASK { get; set; }
        public string USUARIGRUP { get; set; }
    }
}
